### ISSUE TITLE
Hey Yeshua

### ISSUE THREAD

**Issue by uncodedmind** [whoisYeshua/Nike-RU-release-checker#1]
Can u help change the code to use in Brazil?

**Comment by whoisYeshua** [comment]
Try this `marketplace(BR)` and `language(pt-br)`

**Comment by uncodedmind** [comment]
i got the error "Couldn`t find this product, try again"

**Comment by whoisYeshua** [comment]
Looks like your region does`n support this API for upcoming release (i colud find only socks with [it](https://api.nike.com/product_feed/threads/v2/?count=21&filter=channelId%28010794e5-35fe-4e32-aaff-cd2c74f89d61%29&filter=marketplace%28BR%29&filter=language%28pt-br%29), lol), your [endpoint](https://www.nike.com.br/DataLayer/ajaxDataLayer), but it doesnt show stock & you need authoriz to access resource

**Comment by whoisYeshua** [comment]
Mb in future your snkrs will start use this api

**Comment by uncodedmind** [comment]
I had a way to check, but now just show "403 Forbidden
Request forbidden by administrative rules." if you have a e-mail, I can show for you

**Comment by whoisYeshua** [comment]
post imgur link here

**Comment by whoisYeshua** [comment]
I got [this array](https://i.imgur.com/PGFHN56.jpg), but i can\`t see AJ1 BAROQUE BROWN here, so mb this endpoint isn\`t 100% what you need

**Comment by uncodedmind** [comment]
Look, I used to check with this Link, where was possible see the quantity in stock..

https://www.nike.com.br/ProductLookup/555088-201 

https://www.nike.com.br/ProductLookup/[STYLE CODE]

**Comment by whoisYeshua** [comment]
mb need to find right headers for request on this endpoint
