### ISSUE TITLE
Hey Yesua

### ISSUE THREAD

**Issue by richardh0128** [whoisYeshua/Nike-RU-release-checker#2]
I was just wondering if you can tell the product numbers like "High", "Low" etc., or is that possible to tell the numbers exactly? Thank you in advance for your answer!

**Comment by whoisYeshua** [comment]
> I was just wondering if you can tell the product numbers like "High", "Low" etc., or is that possible to tell the numbers exactly? Thank you in advance for your answer!

Stock are obtained from the server, so you can't find out the exact numbers

**Comment by richardh0128** [comment]
I can't check HU region, can you help me? Also RU didn't work for me tbh, my e-mail is richardhonti01@gmail.com

**Comment by whoisYeshua** [comment]
I forgot to add a parameter like channelid to the README, so try [this endpoint](https://api.nike.com/product_feed/threads/v2/?count=14&filter=marketplace%28HU%29&filter=language%28hu%29&filter=channelId%28010794e5-35fe-4e32-aaff-cd2c74f89d61%29)

**Comment by richardh0128** [comment]
Thanks man, but I have no idea what to do with it, I'm not really an IT guy haha

**Comment by whoisYeshua** [comment]
You need to handle this JSON response, the easiest way to do this is with JS , check this [guide](https://javascript.info/json)

**Comment by richardh0128** [comment]
Can I see the stock from the api? I can't handle what I need to handle, hahaha

**Comment by whoisYeshua** [comment]
Clone my repo and change in VS code \ webstorm \ Notepad parameters: `language()` and `marketplace()` for your region, also you could only get "oos", "na", "low", "medium" or "high" value. Maybe in future i will add others regions besides Russia.

**Comment by richardh0128** [comment]
Oh, that was in the README, I've done that. But according to that, the stock is the same in GB, HU, and RU, which I find really really strange.

**Comment by whoisYeshua** [comment]
Hm, I checked stock on RU region and actual stock is [difference ](https://imgur.com/a/qc5aEGj ) then on HU region.
